config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
class ImageUploader < Shrine

end

app/models/product.rb
class Product < ApplicationRecord
  include ImageUploader::Attachment(:image)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(id: :desc)
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(:image, :name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="card mt-5" style="width: 18rem;">
          <%= image_tag product.image_url || "no-pict.png", class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to product.name.titleize, product_path(product) %></h5>
            <p class="card-text">Rp. <%= product.price %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container my-5">
  <%= form_for(@product, url: { action: :create } ) do |f| %>
    <div class="row">
      <div class="col-md-4">
        <%= image_tag "no-pict.png", id: "imageProduct", class: 'img-product' %>
        <div class="form-group form-file">
          <%= f.file_field :image, class: 'form-control-file', id: "productUploader" %>
        </div>
      </div>
      <div class="col-md-8">
        <div class="form-group">
          <label>Name Product</label>
          <%= f.text_field :name, class: 'form-control pt-2' %>
        </div>
        <div class="form-group">
          <label>Description</label>
          <%= f.text_area :description, class: 'form-control pt-2', rows: 5 %>
        </div>
        <div class="form-group">
          <label>Price</label>
          <%= f.number_field(:price, class: 'form-control') %>
        </div>
        <%= f.submit 'Save Product', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end%>
</div>

<script>
  document.getElementById("productUploader").onchange = function () {
    var reader = new FileReader();
    reader.onload = function (e) {
      document.getElementById("imageProduct").src = e.target.result;
    };
    reader.readAsDataURL(this.files[0]);
  };
</script>

app/views/products/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag @product.image_url || "no-pict.png", class: 'img-product' %>
    </div>
    <div class="col-md-6">
      <h3><%= @product.name %></h3>
      <hr>
      <h5>Rp. <%= @product.price %> / Unit</h5>
      <div class="card w-100 mt-3" style="width: 18rem;">
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted">Description</h6>
          <p class="card-text"><%= @product.description %></p>
        </div>
      </div>
      <div class="qty mt-3 text-center">
        <div class="checkout">
          <button type="button" class="decrease-btn">-</button>  
          <input type="text" class="product-value" value="1"> 
          <button type="button" class="increase-btn">+</button>	  
        </div>
      </div>
    </div>
    <div class="col-md-3 text-center">
      <h4>TOTAL</h4>
      <h5 class="checkout">Total: <span id="total">Rp. <%= @product.price %></span></h5>
      <hr>
      <button type="button" class="btn btn-success w-100 mt-1 ">Add to Cart</button>
    </div>
  </div>
</div>



<script>
  /*For total*/
  $(document).ready(function() {
    $(".checkout").on("input", ".product-value", function() {
      var price = +$(".price").data("price");
      var quantity = +$(this).val();
      $("#total").text("Rp. " + <%= @product.price %> * quantity);
    })

    var $buttonPlus = $('.increase-btn');
    var $buttonMin = $('.decrease-btn');
    var $quantity = $('.product-value');
    
    /*For plus and minus buttons*/
    $buttonPlus.click(function() {
      $quantity.val(parseInt($quantity.val()) + 1).trigger('input');
    });
    
    $buttonMin.click(function() {
      $quantity.val(Math.max(parseInt($quantity.val()) - 1, 0)).trigger('input');
    });
  })
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "ONLINE SHOP", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Dashboard</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Products
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Add Product', new_product_path, class: 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Cart</span></a>
        </li>
      </ul>
    </div>
  </div>
</nav>